version: '3'
services:
  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data
  vrcws:
    image: er1807/vrcws:latest
    restart: unless-stopped
    environment:
      REDIS: 'redis'
    depends_on:
      - "redis"
    ports:
      - '8080:8080'
      - '9100:9100'
volumes:
  redisdata:
